---
title: "Air Pressure"
author: "Jonny Behrens"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
      out_dir <- "output";
      rmarkdown::render(inputFile, encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output:
  html_document: 
    theme: cosmo
---

# Set-Up R Environment

```{r setup, echo = FALSE, warning= FALSE, message=FALSE, results='hide'}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

## Set project directory 
projdir <- getwd() # Make sure you have the R Project open! 

## Clear environment
rm(list = ls())

## Libraries
library(pacman)
p_load(tidyverse, StreamPULSE, imputeTS)
```

# Download Data

```{r}
# load in streampulse data that has been gap filled (this is done in a separate RMD file)
dataset_raw<- read_csv("data/rating_curves/air-water_gap-filled_pressure.csv")

# pull in concerning datapoints
flags<-readRDS("data/raw/NC_NHC_raw.rds")
flags<-flags$data %>%
  pivot_wider(names_from = "variable", values_from = "value") %>%
  select(DateTime_UTC, WaterPres_kPa, flagtype, flagcomment)
```

# Prep Data

```{r}
# prep the data
dataset_raw<-dataset_raw %>% 
  left_join(flags) %>% 
  select(DateTime_UTC, AirPres_Gap_filled_with_SP_RDU, WaterPres_kPa, hourlyprecipitation, 
         Data_Source, flagtype, flagcomment) %>%
  # date information
  mutate(DateTime_UTC = ymd_hms(DateTime_UTC)) %>%
  mutate(year = year(DateTime_UTC)) %>% 
  mutate(day = yday(DateTime_UTC)) %>% 
  # marking data for viz
  mutate(missing_waterPres = if_else(is.na(WaterPres_kPa), "Missing WaterPres Data",
                                 if_else(str_detect(flagtype, "Bad|Question"), "Bad or Questionable Data",
                                         "No flags")))
                                 
```

## View Missing data

```{r}
missing1<-dataset_raw %>% 
  filter(year > 2019) %>%
  ggplot(aes(x=DateTime_UTC, y=hourlyprecipitation, color=missing_waterPres)) + 
  geom_point() +
  theme_classic() + 
  theme(legend.position = "bottom")
  
missing2<-dataset_raw %>% 
  filter(year < 2019) %>%
  ggplot(aes(x=DateTime_UTC, y=hourlyprecipitation, color=missing_waterPres)) + 
  geom_point() +
  theme_classic() + 
  theme(legend.position = "bottom")

missing1
missing2
```

# Calculate Q

```{r}
Calculated_values<-dataset_raw %>% 
  # barometric compensation in kPa
  mutate(Level_comp_inital = if_else(is.na(WaterPres_kPa) | is.na(AirPres_Gap_filled_with_SP_RDU), NA,
                              WaterPres_kPa - AirPres_Gap_filled_with_SP_RDU)) %>%
  group_by(year, day) %>% 
  mutate(concerning_value_in_day = any(Level_comp_inital < 1)) %>% 
  ungroup() %>% 
  mutate(Level_comp2 = if_else(Level_comp_inital <= 1, NA, 
                           if_else(missing_waterPres == "No flags", Level_comp_inital, NA))) %>% 
  mutate(small_gap_fill = 
           na_interpolation(Level_comp2, option="linear", maxgap=8)) %>% 
  mutate(Level_comp = if_else(is.na(Level_comp2), small_gap_fill, Level_comp2)) %>% 
  
  
  # conversion to level height, in m (water column equivalent 1 kPa= 0.101972 m)
  mutate(depth = Level_comp * 0.101972) %>% 
  # apply rating curve: y = 3.0903* x ^ 4.2652'
  # 4-22-22: rating curve w extra Q values: y=2.5204 * x^4.3128'
  mutate(Q_mannings = 2.5662 * (depth^2.7534)) %>% 
  mutate(Q_ratingcurve = 2.5204 * (depth^4.3128)) %>% 
  # only keep the important columns
  select(DateTime_UTC, Level_comp, depth, Q_mannings, Q_ratingcurve,year,Level_comp2,Data_Source,small_gap_fill) %>% 
  filter(DateTime_UTC < as.Date("2023-03-01"))
```

```{r}
years=c(2016:2023)

 for (i in 1: length(years)) {
   
   plot<-Calculated_values %>% 
     filter(year == years[i]) %>% 
     mutate(color = if_else(is.na(Level_comp2), "Data Interpolated", "Data Existing")) %>% 
     ggplot(aes(x=DateTime_UTC, y=Level_comp, color = Data_Source)) +
     geom_point() + 
     geom_hline(yintercept = 1, color = "green") +

    # facet_wrap(~year, ncol = 3, scales = "free_x") +
     theme_classic() + 
     theme(legend.position = "bottom") + 
     labs(title = paste((years[i])))

   print(plot)              }

# Calculated_values_P<-Calculated_values %>% 
#   #filter(neg_value_in_day == "TRUE") %>% 
# 
# 
# Calculated_values_P
```

```{r}
   plot<-Calculated_values %>% 
     filter(DateTime_UTC < as.Date("2018-10-15")) %>% 
     filter(DateTime_UTC > as.Date("2018-10-05")) %>% 
     mutate(color = if_else(is.na(Level_comp2), "Data Interpolated", "Data Existing")) %>% 
     ggplot(aes(x=DateTime_UTC, y=small_gap_fill, color = Data_Source)) +
     geom_point() + 
     geom_hline(yintercept = 1, color = "green") +

    # facet_wrap(~year, ncol = 3, scales = "free_x") +
     theme_classic() + 
     theme(legend.position = "bottom") + 
     labs(title = "2018")

   print(plot)    
```



Save the data

```{r}
data_for_modeling<-Calculated_values %>% 
  select(-c(year,Level_comp2,Data_Source,small_gap_fill)) %>% 
  na.omit() %>% 
  filter(DateTime_UTC >= as.Date("2016-09-30"))
  
write.csv(data_for_modeling, "data/rating_curves/hydro_nhc-q_5-4-2023.csv")

```

# OLD CODE

Old code, created by Brooke Hassett.

```{r}
# NHCQplot <- ggplot(NHClevel, aes(x=DateTime_UTC, y=Q_ratingcurve)) + 
#   geom_point() + 
#   labs(title="NHC discharge", x="", y = "Q (m3/s)")+ 
#   scale_x_date(date_labels = "%m-%Y")+
#   theme_classic()  
# 'checking level data'
# NHClevelplot <- ggplot(NHClevel, aes(x=DateTime_UTC, y=depth))+
#   geom_point()+
#   labs(title="NHC level", x="", y="level(m")+
#   scale_x_date(date_labels = "%m-%Y")+
#   theme_classic()
# 'read in NHC 2019-2020 data'
# NHCdata <- read.csv("C:\\Users\\bhassett\\Documents\\R\\SPdata_2022-02-14_NHC\\NC_NHC_SensorData.csv", header=TRUE, stringsAsFactors = FALSE)
# as.data.frame(NHCdata)
# 'barometric pressure compensation- need to separate out variables since DO is in this dataset'
# NHC_airpres <- subset(NHCdata, variable == "AirPres_kPa", select = c("DateTime_UTC", "variable", "value"))
# NHC_waterpres  <- subset(NHCdata, variable == "WaterPres_kPa", select = c("DateTime_UTC", "variable", "value"))
# NHCdata_combined <- merge(NHC_waterpres, NHC_airpres, by="DateTime_UTC")
# NHCdata_combined$level <- NHCdata_combined$value.x - NHCdata_combined$value.y
# 'NHClevel <- ddply(NHCdata_combined, .(DateTime_UTC), summarize, Level_comp=diff(value))'
# 
# 'water column equivalent 1 kPa= 0.101972 m'
# NHCdata_combined$stage <- NHCdata_combined$level * 0.101972
# 'apply rating curve: y = 3.0903* x ^ 4.2652'
# 'try mannings curve: y = 2.5662 * x^2.7534'
# x <- NHCdata_combined$stage 
# NHCdata_combined$Q_mannings = 2.5662 * (x ^ 2.7534)
# NHCdata_combined$Q_hand = 3.0903 * (x ^ 4.2652)
# NHCdata_combined$Q_combined = 1.5812 * (x ^2.5068)
# 'plot data'
# NHCdata_combined$DateTime_UTC <- as.Date(NHCdata_combined$DateTime_UTC)
# 
# NHCQplot <- ggplot(NHCdata_combined, aes(x=DateTime_UTC, y=Q_hand)) + 
#   geom_point() + 
#   labs(title="NHC Q- hand measure", x="", y = "Q (m3/s)")+ 
#   scale_x_date(date_labels = "%m-%Y")+
#   theme_classic()  
# 
# NHCQplot_mannings <- ggplot(NHCdata_combined, aes(x=DateTime_UTC, y=Q_mannings)) + 
#   geom_point() + 
#   labs(title="NHC Q- mannings estimate", x="", y = "Q (m3/s)")+ 
#   scale_x_date(date_labels = "%m-%Y")+
#   theme_classic()
# 
# NHCQplot_combined <- ggplot(NHCdata_combined, aes(x=DateTime_UTC, y=Q_combined)) + 
#   geom_point() + 
#   labs(title="NHC Q-combined curve", x="", y = "Q (m3/s)")+ 
#   scale_x_date(date_labels = "%m-%Y")+
#   theme_classic()```

```

